#!/bin/bash
# /etc/init.d/web_admin_d

### BEGIN INIT INFO
# Provides:          web_admin_d
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: web admin demon
# Description:       used to manage server 
### END INIT INFO

case "$1" in 
  start)
    LOGFILE="log/output.txt"
    cd /home/{{deploy_user}}/apps/web_admin
    mkdir -p log
    echo "Starting web_admin_d" > $LOGFILE
    date >> $LOGFILE
    whoami >> $LOGFILE
    echo $PATH >> $LOGFILE
    which ruby >> $LOGFILE
    which thin >> $LOGFILE
    which gem  >> $LOGFILE
    gem list   >> $LOGFILE
    RACK_ENV=production bin/run > $LOGFILE 2>&1 &
    ;;
  stop)
    echo "Stopping web_admin_d"
    pkill -f web_admin_d
    ;;
  *)
    echo "Usage: /etc/init.d/web_admin_d start|stop"
    exit 1
    ;;
esac

exit 0

