#!/usr/bin/env bash

source `dirname $0`/../bin/util

./sdconfig/set_hostname    &&
./sdconfig/set_sshd        &&
./sdconfig/set_sshkeys     &&
./sdconfig/set_aptcacher   &&
./sdconfig/netboot_cmdline &&
./sdconfig/netboot_fstab   &&
./sdconfig/netboot_nfs     

wrap_up $? "insert SD card into RPi, boot, then run ci/build_snapshot"
