#!/usr/bin/env ruby

# This script creates a disk snapshot.
#
# Use `prep_snapshot revert` to revert to clean root...

ER        = "/export/raspbian"
ERM       = "#{ER}/master"
ERA       = "#{ER}/active"
ERA_ROOT  = "#{ERA}/root"
ERM_ROOT  = "#{ERM}/root"
ERM_CLEAN = "#{ERM}/clean"
ONDECK    = "#{ER}/ondeck"

def abort_unless(*paths)
  paths.each do |path|
    abort "Error - no #{path}" unless Dir.exist?(path)
  end
end

if %w(revert restore rollback).include? ARGV[0]
  puts "Reverting snapshot..."
  abort_unless ERM_CLEAN 
  puts   "Removing old files..."
  system "sudo rm -rf #{ERA_ROOT} #{ONDECK} #{ERM_ROOT}"
  puts   "Restoring #{ERM_ROOT}..."
  system "sudo cp -a #{ERM_CLEAN} #{ERM_ROOT}" 
  puts   "Restoring #{ERA_ROOT}..."
  system "sudo cp -a #{ERM_CLEAN} #{ERA_ROOT}" 
  puts   "Restoring #{ONDECK}..."
  system "sudo cp -a #{ERM_CLEAN} #{ONDECK}" 
  exit
end

abort_unless ERA_ROOT, ERM_ROOT

puts   "Removing stale cache..."
system "sudo rm -rf #{ONDECK}"

puts   "Creating clean backup..."
system "sudo mv #{ERM_ROOT} #{ERM_CLEAN}" unless Dir.exist?(ERM_CLEAN) 

puts   "Removing old master..."
system "sudo rm -rf #{ERM_ROOT}"               

puts   "Creating snapshot..."
system "sudo cp -a #{ERA_ROOT} #{ERM_ROOT}"

puts   "Creating cache..."
system "sudo mkdir -p #{ONDECK}"
system "sudo cp -a #{ERM_ROOT} #{ONDECK}/root" 

puts   "Export Directory Stats..."
system "sudo du -s --time /export/raspbian/*/*"

puts "Done."
