#!/bin/bash

# This script updates the file $sd_root/etc/fstab with instructions that
# cause the RPi to auto-mount the NFS drive on boot.

source ./bin/util

TAB_FILE=$sd_root/etc/fstab

setblock TAB_TEXT << EOF
proc            /proc           proc    defaults        0  0
/dev/mmcblk0p1  /boot           vfat    defaults        0  2
/dev/nfs        /               rootfs  defaults,rw  
tmpfs  /tmp     tmpfs  nodev,nosuid,size=10%,mode=1777  0  0
tmpfs  /var/log tmpfs  nodev,nosuid,size=20%,mode=1755  0  0
EOF

[ -n $sd_root ] || raise "No SD root partition..."
[ -d $sd_root ] || raise "SD root directory $sd_root not found"
[ -d $sd_base ] || raise "SD base directory $sd_base not found"

backup_file $TAB_FILE

echo "$TAB_TEXT" >> /tmp/tab

sudo cp /tmp/tab $TAB_FILE
sudo touch $SD_ROOT/tmp/.tmpfs

echo Text written to $TAB_FILE
echo "$TAB_TEXT"

msg "DONE"
