#!/bin/bash

# This script assumes that the SD card is mounted at /media.  It copies the
# contents of the SD card on /media to the NFS drives at /export/raspbian.

source ./bin/util

[ -n $sd_root ] || raise "no SD root directory"
[ -d $sd_base ] || raise "sd SD base directory $sd_base not found" 
[ -d $sd_boot ] || raise "sd SD boot directory $sd_boot not found"

stop_ondeck_backup

msg  "Removing old $erpi_base directory..."
sudo rm -rf $erpi_base

msg  "Creating new $erpi_base directories..."
sudo mkdir -p $erpi_base/active
sudo mkdir -p $erpi_base/master
sudo mkdir -p $erpi_base/ondeck

msg  "Copying master boot directory (runs fast!)..."
sudo cp -a $sd_boot $erpi_master_boot

msg  "Copying master root directory (runs slow!)..."
sudo cp -a $sd_root $erpi_master_root

msg  "Creating active root directory (runs slow!)..."
sudo cp -a $erpi_master_root $erpi_active_root

create_ondeck_backup

msg  "DONE"
