#!/bin/bash

# This script updates the file $sd_boot/cmdline.txt with instructions that
# cause the RPi to boot from a NFS drive.

source `dirname $0`/../bin/util

CMDLINE_FILE=$sd_boot/cmdline.txt
LOCAL_IP=`local_ip_address`

[ -f $CMDLINE_FILE ] || raise "file $CMDLINE_FILE not found"
[ -n $LOCAL_IP     ] || raise "no IP address!!"

CMDLINE_TEXT="dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 ip=dhcp root=/dev/nfs nfs-options=hard,intr,rw,size=32768,wsize=32768 rootfstype=nfs elevator=deadline rootwait nfsroot=$LOCAL_IP:/export/raspbian/active/root rootpath=/export/raspbian/active/root"

backup_file $CMDLINE_FILE

sudo echo $CMDLINE_TEXT > $CMDLINE_FILE

echo "Netboot command line written to $CMDLINE_FILE"
echo $CMDLINE_TEXT

msg "DONE"
