#!/bin/bash

# This script assumes that the SD card is mounted at /media.  It updates the
# file /media/boot/cmdline.txt with instructions the cause the RPi to boot from
# a NFS drive.

source ./bin/util

CMDLINE_FILE=$sd_boot/cmdline.txt
LOCAL_IP=`local_ip_address`

[ -f $CMDLINE_FILE ] || raise "ERROR - file $CMDLINE_FILE not found"

cmdline="dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 ip=dhcp root=/dev/nfs nfs-options=hard,intr,rw,size=32768,wsize=32768 rootfstype=nfs elevator=deadline rootwait nfsroot=$LOCAL_IP:/export/raspbian/active/root rootpath=/export/raspbian/active/root"

backup_file $CMDLINE_FILE

sudo echo $cmdline > $CMDLINE_FILE

echo "Netboot command line written to $CMDLINE_FILE"
echo $cmdline
