#!/bin/bash

# This script assumes that the SD card is mounted at /media.  It updates the
# file /media/<path>/etc/fstab with instructions the cause the RPi to
# auto-mount the NFS drive on boot.

source ./bin/util
load_environment_variables
print_header

TAB_FILE=$sd_root/etc/fstab
BACKUP_FILE   = "#{TAB_FILE}.backup.#{Time.now.strftime('%y%m%d_%H%M%S')}"

TAB_TEXT = <<-EOF
proc            /proc           proc    defaults        0  0
/dev/mmcblk0p1  /boot           vfat    defaults        0  2
/dev/nfs        /               rootfs  defaults,rw  
tmpfs  /tmp     tmpfs  nodev,nosuid,size=10%,mode=1777  0  0
tmpfs  /var/log tmpfs  nodev,nosuid,size=20%,mode=1755  0  0
EOF

def err(msg)
  abort "ERROR - #{msg}"
end

err "sd base directory #{SD_BASE} not found" unless Dir.exist?(SD_BASE)
err "sd partitions at #{SD_BASE} not found"  unless SD_PARTITIONS.length == 2
err "no SD root partition"                   if SD_ROOT.nil?

system "sudo cp #{TAB_FILE} #{BACKUP_FILE}"
File.open("/tmp/tab", 'w') {|f| f.puts TAB_TEXT}
system "sudo cp /tmp/tab #{TAB_FILE}"
system "sudo touch #{SD_ROOT}/tmp/.tmpfs"

puts "Text written to #{TAB_FILE}\n#{TAB_TEXT}"
