---

# ntpd

- name: install support packages
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - ntp            # Main ntpd server
  
- name: install ntpd conf file
  sudo: true
  copy: 
    src: ntp.conf
    dest: /etc/ntp.conf
    mode: "a+rx"

