---

# tmux

- name: add PPA (ubuntu 1404)
  sudo: true
  when: is_ubuntu_1404
  apt_repository: repo="ppa:pi-rho/dev" 

- name: add PPA (ubuntu 1204)
  sudo: true
  # when: is_ubuntu_1204
  apt_repository: repo="ppa:kalakris/tmux" 

- name: install (ubuntu)
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  when: is_ubuntu
  with_items:
    - tmux

- name: copy tmux executable (rpi)
  sudo: true
  when: is_rpi
  copy:
    src: rpi/tmux
    dest: /usr/local/bin/tmux
    mode: 'a+rx'

# wemux

- name: install github repo
  git:
    repo:   "https://github.com/zolrath/wemux.git"
    dest:   "/usr/local/share/wemux"
    depth:  1
    force:  true
    update: true

- name: create symlink to executable
  file: 
    src: /usr/local/share/wemux/wemux
    dest: /usr/local/bin/wemux
    mode: "a+rx"
    state: link 

- name: install wemux.conf
  template:
    src: wemux.conf
    dest: /usr/local/etc/wemux.conf


