---

# cli_user
#
# Pastfix gmail setup guide from here: 
#   https://rtcamp.com/tutorials/linux/ubuntu-postfix-gmail-smtp/
# invoke using:
# - {role: cli_user, rem_user: "<username>"}

- name: install support packages
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
       - mailutils 
       - libsasl2-2 
       - ca-certificates 
       - libsasl2-modules

- name: set postfix install options
  sudo: true
  shell: echo 'postfix postfix/mailname string {{rpi_name}}' | debconf-set-selections

- name: set postfix install options 2
  sudo: true
  shell: echo 'postfix postfix/relayhost       string  {{relay_host}}' | debconf-set-selections

- name: set postfix install options 3
  sudo: true
  shell: echo 'postfix postfix/main_mailer_type        select  Internet with smarthost' | debconf-set-selections

- name: install support packages
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - postfix     # Linux mail server
    - wget
    - cron        # Likley already installed, but making sure

- name: install call home script
  sudo: true
  copy: 
    src: call-home-script.bash
    dest: /bin/call-home-script.bash
    mode: "a+rx"

# Alter call home script
- replace: dest=/bin/call-home-script.bash regexp='<hostname>' replace={{ ansible_nodename }} backup=yes
- replace: dest=/bin/call-home-script.bash regexp='home-email' replace='{{call_home_email}}' backup=no

- name: install call home cron script
  sudo: true
  copy: 
    src: run-call-home.bash
    dest: /bin/run-call-home.bash
    mode: "a+rx"

- name: install call home cron job
  sudo: true
  copy: 
    src: call-home-cron
    dest: /etc/cron.d/call-home
    mode: "a+rx"

- name: Test sasl auth in postfix config
  shell: grep "^smtp_sasl_auth_enable = yes" /etc/postfix/main.cf
  register: test_grep

- name: add sasl auth
  sudo: true
  lineinfile: dest=/etc/postfix/main.cf line="smtp_sasl_auth_enable = yes"
  when: test_grep.stdout != ""

- name: Test for password map in postfix config
  shell: grep "^smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd" /etc/postfix/main.cf
  register: test_grep

- name: add password map
  sudo: true
  lineinfile: dest=/etc/postfix/main.cf line="smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd"
  when: test_grep.stdout != ""

- name: Test noanon in postfix config
  shell: grep "^smtp_sasl_security_options = noanonymous" /etc/postfix/main.cf
  register: test_grep

- name: add noanon to postfix conf 
  sudo: true
  lineinfile: dest=/etc/postfix/main.cf line=""
  when: test_grep.stdout != "smtp_sasl_security_options = noanonymous"

- name: Testtls cafile  in postfix config
  shell: grep "^smtp_tls_CAfile = /etc/postfix/cacert.pem" /etc/postfix/main.cf
  register: test_grep

- name: add to postfix conf 
  sudo: true
  lineinfile: dest=/etc/postfix/main.cf line="smtp_tls_CAfile = /etc/postfix/cacert.pem"
  when: test_grep.stdout != ""

- name: Test smtp_use_tls in postfix config
  shell: grep "^smtp_use_tls = yes" /etc/postfix/main.cf
  register: test_grep

- name: add smtp_use_tls to postfix conf 
  sudo: true
  lineinfile: dest=/etc/postfix/main.cf line="smtp_use_tls = yes"
  when: test_grep.stdout != "smtp_use_tls = yes"

- name: install sasl password file
  sudo: true
  copy: 
    src: sasl_passwd
    dest: /etc/postfix/sasl_passwd
    mode: "400"

- name: Gen sasl password file
  sudo: true
  shell: /usr/sbin/postmap /etc/postfix/sasl_passwd

- name: restart postfix
  sudo: true
  shell: /usr/sbin/service postfix restart

- name: restart cron
  sudo: true
  shell: /usr/sbin/service cron restart

