#!/usr/bin/env bash

# copy the 'reporter' script to the client machine

source `dirname $0`/../../bin/util

host=$1

[ -z $host ]      && raise "must specify a hostname"
can_not_ssh $host && raise "can not ssh $host"

if [ -n "$default_lat" ]; then
  msg "Setting up default GPS coordinates on $host"
  msg "Default Lat: $default_lat"
  msg "Default Lon: $default_lon"
  echo -e "$default_lat\n$default_lon" > /tmp/gpsdef
  scp /tmp/gpsdef $host:/tmp/default_latlon > /dev/null 2>&1
  ssh $host sudo mkdir -p /usr/local/share/tracker
  ssh $host sudo mv /tmp/default_latlon /usr/local/share/tracker
  ssh $host sudo chmod a+rx /tmp/default_latlon 
fi

destination=/usr/local/bin/reporter

msg "Copy tracker/client/reporter to $host:$destination"
scp tracker/client/reporter $host:/tmp/reporter > /dev/null 2>&1
ssh $host sudo mv /tmp/reporter $destination
ssh $host sudo chmod a+rx $destination

msg "DONE"
