#!/usr/bin/env bash

source `dirname $0`/../../bin/util

host=$1

usage="USAGE: `basename $0` <hostname>"

[ -z $host ]      && raise "must specify a hostname\n$usage"
can_not_ssh $host && raise "can not ssh $host"

setblock CRON_TEXT << EOT
* * * * * root command /usr/local/bin/reporter
EOT

msg "Setting up Tracker cron on $host"
echo -e "$CRON_TEXT" > /tmp/cron_text
cat /tmp/cron_text
scp /tmp/cron_text $host:/tmp/cron_text > /dev/null 2>&1
ssh $host sudo mv /tmp/cron_text /etc/cron.d/tracker
ssh $host sudo chmod a+r  /etc/cron.d/tracker
ssh $host sudo chmod a-wx /etc/cron.d/tracker
ssh $host sudo chown root:root /etc/cron.d/tracker
ssh $host sudo /etc/init.d/cron restart > /dev/null 

msg "DONE"
