#!/usr/bin/env bash

source `dirname $0`/../../bin/util

host=$1

[ -z $host ]      && raise "must specify a hostname"
can_not_ssh $host && raise "can not ssh $host"

ssh $host ~/.reporter

msg "DONE"
