#!/usr/bin/env ruby

require 'wemote'
require 'typhoeus'

# Use this script to control Belkin Wemo switches.
# Relies on the Wemote gem: see https://github.com/gisikw/wemote

SWITCH_NAME = "RPi Switch"

opts = %w(on off toggle powercycle)
msg  = "Usage: set_wemo <#{opts.join('|')}>"

abort(msg) if ARGV.length != 1
arg = ARGV[0]
abort("ERROR - Unrecognized option: #{arg}\n#{msg}") unless opts.include?(arg)

switch = Wemote::Switch.find(SWITCH_NAME)

abort "ERROR - Wemo switch not found: #{SWITCH_NAME}" if switch.nil?

case arg
when "on"             then switch.on!
when "off"            then switch.off!
when "toggle"         then switch.toggle!
when "powercycle"     then switch.off! ; sleep 2 ; switch.on!
end

