#!/usr/bin/env ruby

require 'socket'

CMDLINE_FILE = "/media/boot/cmdline.txt"
BACKUP_FILE  = "#{CMDLINE_FILE}.backup.#{Time.now.strftime('%y%m%d_%H%M%S')}"

def local_ip
  orig = Socket.do_not_reverse_lookup  
  Socket.do_not_reverse_lookup = true # turn off reverse DNS resolution temporarily
  UDPSocket.open do |socket|
    socket.connect '64.233.187.99', 1 # google
    socket.addr.last
  end
ensure
  Socket.do_not_reverse_lookup = orig
end

cmdline = "dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 ip=dhcp root=/dev/nfs nfs-options=hard,intr,rw,size=32768,wsize=32768 rootfstype=nfs elevator=deadline rootwait nfsroot=#{local_ip}:/export/raspbian/active/root rootpath=/export/raspbian/active/root"

msg = "ERROR - file #{CMDLINE_FILE} not found"
abort msg unless File.exist?(CMDLINE_FILE)

system "sudo cp #{CMDLINE_FILE} #{BACKUP_FILE}"
File.open(CMDLINE_FILE, 'w') {|f| f.puts cmdline}

puts "Netboot command line written to #{CMDLINE_FILE}\n#{cmdline}"
