#!/usr/bin/env ruby

require 'fileutils'

CMDLINE_FILE = "/media/boot/cmdline.txt"
BACKUP_FILE  = "#{CMDLINE_FILE}.backup.#{Time.now.strftime('%y%m%d_%H%M%S')}"

nfs_target = ENV["SYSNAME"]

cmdline = "dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 ip=dhcp root=/dev/nfs nfs-options=hard,intr,rw,size=32768,wsize=32768 rootfstype=nfs elevator=deadline rootwait nfsroot=#{nfs_target}:/export/raspbian/working rootpath=/export/raspbian/working"

msg = "ERROR - file #{CMDLINE_FILE} not found"
abort msg unless File.exist?(CMDLINE_FILE)

system "sudo cp #{CMDLINE_FILE}, #{BACKUP_FILE}"
File.open(CMDLINE_FILE, 'w') {|f| f.puts cmdline}

puts "Netboot command line written to #{CMDLINE_FILE}\n#{cmdline}"
