require 'rake'
require 'rspec/core/rake_task'
require 'colored'

HR    = "\n#{'*'*60}"
Host  = Struct.new(:name, :phase)
names = %w(cat1.phase1 cat2.phase1)
hosts = names.map {|x| Host.new(*x.split('.'))}

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  task :all => hosts.map {|h| "spec:#{h.name}"}
  hosts.each do |host|
    desc "Run serverspec for #{host.name}/#{host.phase}"
    RSpec::Core::RakeTask.new(host.name) do |t|
      ENV['TARGET_HOST']  = host.name
      ENV['TARGET_PHASE'] = host.phase
      puts HR.yellow
      puts "TEST TARGET: #{host.name}/#{host.phase}".yellow
      t.verbose = false
      t.pattern = "spec/#{host.phase}/*_spec.rb"
    end
  end
end

