require 'rake'
require 'rspec/core/rake_task'

Host  = Struct.new(:name, :role)
names = %w(cat1.base cat2.base)
hosts = names.map {|x| Host.new(*x.split('.'))}

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  task :all => hosts.map {|h| "spec:#{h.name}"}
  hosts.each do |host|
    desc "Run serverspec to #{host.name}"
    RSpec::Core::RakeTask.new(host.name) do |t|
      ENV['TARGET_HOST'] = host.name
      puts "HOST IS #{host.name}"
      t.pattern = "spec/#{host.role}/*_spec.rb"
    end
  end
end

