---

# gpsd

- name: install support packages
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - usbutils      # Utilities to examine usb devices
    - minicom       # Tool useful to diagnose what is going on with a tty device
    - python-serial # Python serial lib
  
- name: install modem status shell file.
  sudo: true
  copy: 
    src: get-modem-status.py
    dest: /bin/get-modem-status.py
    mode: "a+rx"


