source "https://rubygems.org"

# for development only
# on production, install gems with ansible

gem "thin"     # web server

gem "sinatra"  # webapp framework

gem "rerun"    # dev server - auto-reloads changed files 
