#!/usr/bin/env bash

source `dirname $0`/../bin/util

DASHBOARD="TRACKER"

dash_init() {
  ./tracker/bin/start all
  ./tracker/bin/cron_setup on
}

dash_shutdown() {
  ./tracker/bin/stop all
  ./tracker/bin/cron_setup off
}

setup_tmux_dashboard() {
  dashboard=$1
  create_tmux_dashboard $dashboard
  tmux_send_keys $dashboard 1 "tail -f tracker/log/server.log"
  tmux_send_keys $dashboard 2 "tail -f tracker/log/worker.log"
  tmux_send_keys $dashboard 3 "tail -f tracker/log/tunnel.log"
}

dash_init

if is_live_dashboard $DASHBOARD; then
  msg "Attaching to existing dashboard"
else
  msg "Creating a new dashboard"
  setup_tmux_dashboard $DASHBOARD
fi
tmux attach -t $DASHBOARD

is_no_live_dashboard $DASHBOARD && dash_shutdown
