#!/bin/bash

source `dirname $0`/../bin/util

serverpid="/tmp/tracker_server.pid"
rackpid="/tmp/tracker_rack.pid"

use_pidfile $serverpid

mkdir -p ./tracker/log ./tracker/data

# start web server
cd tracker

kill_pidfile $rackpid

if [ "$RACK_ENV" == "production" ]; then
  rackup -o 0.0.0.0 -p 9191 &
else
  shotgun -o 0.0.0.0 -p 9191 &
fi

set_pidfile $rackpid $!
