---

# cli_base_rpi

- name: install base packages
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=no
  with_items:
    - python-software-properties # required by apt-get
    - python-pip                 # required by ansible
    - python-dev                 # required by ansible
    - python-virtualenv          # required by ansible
    - build-essential            # compile tools
    - dnsutils                   # dnsutils
    - git-core                   # git
    - aptitude                   # package manager
    - cmake                      # required by libgit2/rugged
    - libicu-dev                 # development lib
    - htop                       # monitoring utility
    - atop                       # monitoring utility
    - ncdu                       # monitoring utility
    - nmon                       # monitoring utility
    - iftop                      # monitoring utility
    - dstat                      # monitoring utility
    - iotop                      # monitoring utility
    - nload                      # monitoring utility
    - sysstat                    # monitoring utility
    - libcurl4-openssl-dev       # development lib
    - libevent-dev               # development lib
    - libncurses5-dev            # development lib
    - libxml2-dev                # development lib
    - libreadline-dev            # development lib
    - libssl-dev                 # development lib
    - libxslt1-dev               # development lib
    - zlib1g-dev                 # development lib
    - multitail                  # log file monitoring
    - tree                       # cli utility
    - curl                       # cli utility
    - wget                       # cli utility
    - unzip                      # cli utility
    - zip                        # cli utility
    - debian-archive-keyring     # ssh util
    - ruby1.9.3                  # ruby
    - exuberant-ctags            # vim file navigation
    - vim-gnome                  # vim!
    - mlocate                    # For locating files on the RPI
    - iptraf                     # IP traffic monitor
    - subversion                 # Alternate scm software
    - strace                     # Util for diagnosing binary problems
    - tcpdump                    # Util for watching ip traffic
    - ntpdate                    # NTP util to suppliment ntpd
    # - redis-server               # redis
    # - postgresql-9.1             # postgres
    # - pgadmin3                   # pgadmin
    # - collectd                   # stats collector

- name: remove packages
  sudo: true
  apt: pkg={{item}} state=absent
  with_items:
    - whoopsie        # ubuntu bug reporter

# - name: upload lang.sh
#   copy: src=lang.sh dest=/etc/profile.d/lang.sh
#   sudo: true

- name: install jq 
  sudo: true
  copy: src=jq dest=/usr/local/bin/jq mode="a+rx"

