#!/bin/bash

source ./ci/util
load_environment_variables
print_header

msg "Powercycle the RPi"
msg "CI Slave->`hostname` RPi->$rpi_hostname"
msg "Powercycle Command: $powercycle_cmd"
$powercycle_cmd

# check to see if machine is pingable
count_down=5
pingable=false
while [ $count_down -gt 0 -a $pingable == false ]; do
  msg "Sleep 10 seconds while the RPi boots (countdown:$count_down)"; sleep 10
  can_ping $rpi_hostname && pingable=true
  let count_down-=1
done

if [ $pingable == true ]; then
  msg "$rpi_hostname is pingable"
else
  msg "$rpi_hostname is not pingable"
  msg "Unsuccessful reboot"
  exit 1
fi

# check for ssh login
count_down=5
sshable=false
while [ $count_down -gt 0 -a $sshable == false ]; do
  msg "Sleep 10 seconds waiting for SSH access (countdown:$count_down)"; sleep 10
  can_ssh pi@$rpi_hostname && sshable=true
  let count_down-=1
done

if [ $sshable == true ]; then
  msg "Can ssh to pi@$rpi_hostname"
  msg "Successful reboot"
  exit 0
else
  msg "Can not ssh to pi@$rpi_hostname"
  msg "Current user is $USER"
  msg "Unsuccessful reboot"
  exit 1
fi

