#!/usr/bin/env bash

source `dirname $0`/../bin/util

focus_arg=""
[ "$1" == "focus_only" ] && focus_arg="--focus only"
[ "$1" == "focus_skip" ] && focus_arg="--focus skip"

[ -n $playbook ] || raise '$playbook not defined'

# Setup ansible enviroment
pwd=$(pwd)
cd $pwd/playbooks

msg "Create inventory file"
echo "[rpi]"                         > inventory/hosts_ci.ini
echo "$rpi_hostname ssid=$rpi_ssid" >> inventory/hosts_ci.ini

msg "Run ansible"
cmd="./config --nopass --inventory ci --playbook $playbook $focus_arg"
msg "$cmd"
$cmd
