#!/bin/bash

source ./bin/ci/util
load_environment_variables
print_header

# Setup ansible enviroment
pwd=$(pwd)
cd $pwd/playbooks

msg "Create inventory file"
echo "[rpi]"                         > inventory/hosts_ci.ini
echo "$rpi_hostname ssid=$rpi_ssid" >> inventory/hosts_ci.ini

msg "Run ansible"
./config --nopass --inventory ci -p $playbook 

