#!/bin/bash

source ./bin/util

focus_arg=""
[ "$1" == "focus_only" ] && focus_arg="-f only"
[ "$1" == "focus_skip" ] && focus_arg="-f skip"

# Setup ansible enviroment
pwd=$(pwd)
cd $pwd/playbooks

msg "Create inventory file"
echo "[rpi]"                         > inventory/hosts_ci.ini
echo "$rpi_hostname ssid=$rpi_ssid" >> inventory/hosts_ci.ini

msg "Run ansible"
cmd="./config --nopass --inventory ci -p $playbook $focus_arg"
msg $cmd
$cmd
