#!/bin/bash

# This script creates a disk snapshot.
#
# Use `snapshot revert` to revert to clean root

source `dirname $0`/../bin/util

if [ "$1" == "revert" ]; then
  msg  "Remove previous know_host settings for $rpi_hostname"
  ssh-keygen -f "/home/$env_username/.ssh/known_hosts" -R $rpi_hostname
  msg "Reverting snapshot"
  if [ ! -d $erpi_master_clean ]; then
    msg "Missing $erpi_master_clean - nothing to revert"
    exit
  fi
  msg  "Removing old files"
  sudo rm -rf $erpi_active_root $erpi_ondeck_root $erpi_master_root
  msg  "Restoring $erpi_master_root"
  sudo cp -a $erpi_master_clean $erpi_master_root 
  msg  "Restoring $erpi_active_root"
  sudo cp -a $erpi_master_clean $erpi_active_root 
  msg  "Restoring $erpi_ondeck"
  sudo mkdir -p $erpi_ondeck 
  sudo cp -a $erpi_master_clean $erpi_ondeck_root
  exit
fi

[ -d $erpi_active_root ] || raise "no $erpi_active_root"
[ -d $erpi_master_root ] || raise "no $erpi_master_root"

msg  "Removing stale cache"
sudo rm -rf $erpi_ondeck_root

msg  "Creating clean backup"
[ -d $erpi_master_clean ] || sudo mv $erpi_master_root $erpi_master_clean 

msg   "Removing old master"
sudo rm -rf $erpi_master_root 

msg  "Creating snapshot (runs slow)"
sudo cp -a $erpi_active_root $erpi_master_root

msg  "Creating cache (runs slow)"
sudo mkdir -p $erpi_ondeck 
sudo cp -a $erpi_master_root $erpi_ondeck_root 

msg  "Export Directory Stats"
sudo du -s --time $erpi/*/*

msg "DONE"
