---

# web_admin

- name: show the git branch
  debug: msg="GIT BRANCH IS {{git_branch}}"
    
- name: install support software
  sudo: true
  apt:  pkg={{item}} state=present install_recommends=no
  with_items:
    - ruby              # interpreter for ruby language
    - ruby-dev
    - bundler
    - ruby-sinatra
    - thin
    - ruby-ffi
    - ruby-rb-inotify

- name: setup gemrc 
  sudo: true
  template:
    src: gemrc
    dest: /root/.gemrc

- name: install ruby gems
  sudo: true
  gem: name={{item}} state=latest
  with_items:
    - rerun
    - celluloid
    - listen
    - timers
    # - hitimer      didn't install on RPi
    # - rb-inotif    didn't install on RPi
    - ffi
    - thin 
    - sinatra

- name: stop the service
  sudo: true
  service: name=web_admin_d state=stopped

- name: remove old repo
  file:
    path: "/home/{{deploy_user}}/apps"
    state: absent

- name: install github repo
  command: "/usr/bin/git clone --depth 1 -b {{git_branch}} {{git_repo}} /home/{{deploy_user}}/apps"

- name: remove extra files
  sudo: true
  file:
    path: "/home/{{deploy_user}}/apps/{{item}}"
    state: "absent"
  with_items:
    - "README.md"
    - "NOTES.md"
    - "bin"
    - "playbooks"
  changed_when: false

- name: set file ownership
  file:
    state: directory
    path:  "/home/{{deploy_user}}/apps"
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    recurse: true

- name: setup init script
  template: 
    src:  web_admin_d
    dest: /etc/init.d
    mode: a+rx

- name: configure log rotation
  sudo: true
  template:
    src: logrotate
    dest: /etc/logrotate.d/web_admin

- name: auto-start the server on reboot
  sudo: true
  shell: "update-rc.d web_admin_d defaults"

- name: start the server
  sudo: true
  service: name=web_admin_d state=started

