---

# web_admin

- name: install support software
  sudo: true
  apt:  pkg={{item}} state=present install_recommends=no
  with_items:
    - ruby              # interpreter for ruby language
    - ruby-dev
    - bundler
    - ruby-sinatra
    - thin
    - ruby-ffi
    - ruby-rb-inotify

- name: setup gemrc 
  sudo: true
  template:
    src: gemrc
    dest: /root/.gemrc

- name: install ruby gems
  sudo: true
  gem: name={{item}} state=latest
  with_items:
    - rerun
    - celluloid
    - listen
    - timers
    - hitimer
    - rb-inotif
    - ffi

- name: install github repo
  git:
    repo:   "https://github.com/cinchcircuits/bamru_truck"
    dest:   "/home/{{deploy_user}}/apps"
    depth:  1
    force:  true
    update: true

- name: remove extra files
  sudo: true
  file:
    path: "/home/{{deploy_user}}/apps/{{item}}"
    state: "absent"
  with_items:
    - "README.md"
    - "NOTES.md"
    - "bin"
    - "playbooks"
  changed_when: false

- name: set file ownership
  file:
    state: directory
    path:  "/home/{{deploy_user}}/apps"
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    recurse: true

- name: setup init script
  template: 
    src:  web_admin_d
    dest: /etc/init.d
    mode: a+rx

- name: configure log rotation
  sudo: true
  template:
    src: logrotate
    dest: /etc/logrotate.d/web_admin

- name: auto-start the server on reboot
  sudo: true
  shell: "update-rc.d web_admin_d defaults"

- name: start the server
  sudo: true
  service: name=web_admin_d state=started

