#!/bin/bash

source ./bin/util

remote_port=9292

case $USER in
  aleak) 
    remote_port=9292
    ;;
  mgregg)
    remote_port=9293
    ;;
esac

mkdir -p ./ghci/log ./ghci/history ./ghci/queue

# start port forwarding in the background
./bin/portfwd $remote_port 9292 > ./ghci/log/portfwd.log &

# start worker in the background
./ghci/worker > ./ghci/log/worker.log &

# start web server
cd ghci
rackup -o 0.0.0.0

