---

# rpi_hotspot
# see http://elinux.org/RPI-Wireless-Hotspot

- name: install support packages
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - usbutils     # Utilities to examine usb devices
    - gpsd         # Main gpsd server
    - gpsd-clients # Supporting client packages
  
- name: install shell script to alter ttyUSBGPS link
  sudo: true
  copy: 
    src: setup-usb-gps.bash
    dest: /bin/setup-usb-gps.bash
    mode: "a+rx"

- name: Populate DEVICES in /etc/default/gpsd
  sudo: true
  lineinfile:
    dest:   /etc/init.d/hostapd
    line:   "DEVICES=\"\""
    regexp: "^DEVICES=\"/dev/ttyUSBGPS\""

- name: auto-start gpsd point on Boot
  sudo:  true
  shell: "{{item}}" 
  with_items:
    - "update-rc.d gpsd enable"

