#!/bin/bash

USAGE="Usage: config [-n|--nopass] [-b|--branch <branchName>] [-d|--deploy_only] [-p|--playbook] [-h|--help]"

# Use the 'nopass' option if ssh-keys have been configured and you want to skip
# the ssh password.

# -------------------------------------------------------------------------------
# Parse command-line options

NOPASS=false
BRANCH="$(git symbolic-ref --short -q HEAD)"
TAGS=""

while [[ $# > 0  ]]
do
  case $1 in
    -h|--help)
      echo $USAGE
      exit
      ;;
    -i|--inventory)
      INVENTORY="$2"
      ;;
    -n|--nopass)
      NOPASS=true
      ;;
    -b|--branch)
      BRANCH="$2"
      shift
      ;;
    -p|--playbook)
      PLAYBOOK="-$2"
      shift
      ;;
    -d|--deploy_only)
      TAGS="--tags deploy"
      ;;
    *)
      echo $USAGE
      echo Unrecognized Option: $1
      exit
      ;;
  esac
  shift
done

# -------------------------------------------------------------------------------
# You can have a user-specific host file.  This option is provided so different
# developers can run ansible independently.  If a user-specific host file is not
# provided, a default file 'inventory/hosts.ini' will be used.

base_hosts="./inventory/hosts.ini"
user_hosts="./inventory/hosts_$USER.ini"
clop_hosts="./inventory/hosts_$INVENTORY.ini"

hosts=$base_hosts
[ -f $user_hosts ] && hosts=$user_hosts 
[ -f $clop_hosts ] && hosts=$clop_hosts 

echo using host file $hosts

# -------------------------------------------------------------------------------
# By default, ansible will ask for the remote user password using the
# '--ask-pass' option. After ssh keys are provisioned, passwords are no longer
# required.  The 'nopass' command line option skips the password prompt.

[[ "$NOPASS" != "true" ]] && echo "Hint: use 'config --nopass' to authenticate with SSH keys"
[[ "$NOPASS" == "true" ]] && arg="" || arg="--ask-pass"

cmd="ansible-playbook -i $hosts -e git_branch=$BRANCH $TAGS rpi$PLAYBOOK.yml $arg"

echo running \"$cmd\"

# -------------------------------------------------------------------------------
$cmd

