#!/bin/bash

USAGE_MSG="Usage: config [-n | --nopass] [-b | --branch <branchName>]"

# Use the 'nopass' option if ssh-keys have been configured and you want to skip
# the ssh password.

# -------------------------------------------------------------------------------
# Parse command-line options

NOPASS=false
BRANCH="master"
TAGS=""

while [[ $# > 0  ]]
do
  case $1 in
    -n|--nopass)
      NOPASS=true
      ;;
    -b|--branch)
      BRANCH="$2"
      shift
      ;;
    -d|--deploy_only)
      TAGS="--tags deploy"
      shift
      ;;
    *)
      echo $USAGE_MSG
      echo Unrecognized Option: $1
      exit
      ;;
  esac
  shift
done

# -------------------------------------------------------------------------------
# You can have a user-specific host file.  This option is provided so different
# developers can run ansible independently.  If a user-specific host file is not
# provided, a default file 'inventory/hosts.ini' will be used. 

base_hosts="./inventory/hosts.ini"
user_hosts="./inventory/hosts_$USER.ini"

[ -f $user_hosts ] && hosts=$user_hosts || hosts=$base_hosts

echo using host file $hosts

# -------------------------------------------------------------------------------
# By default, ansible will ask for the remote user password using the
# '--ask-pass' option. After ssh keys are provisioned, passwords are no longer
# required.  The 'nopass' command line option skips the password prompt.

[[ "$NOPASS" != "true" ]] && echo "Hint: use 'config --nopass' to authenticate with SSH keys"
[[ "$NOPASS" == "true" ]] && arg="" || arg="--ask-pass"

cmd="ansible-playbook -i $hosts -e git_branch=$BRANCH $TAGS rpi.yml $arg"

echo running \"$cmd\"

# -------------------------------------------------------------------------------
$cmd

