---
# USE THE CONFIG SCRIPT TO BRING UP A NEW MACHINE

- hosts:      rpi   
  vars:
    - lcl_user:  "{{ lookup('env', 'USER') }}"
    - rem_user:  pi                
  remote_user: "{{rem_user}}"
  sudo: true
  roles:
    - roles/check_env
    - { role: roles/setup_ssh , rem_user: "pi"     }
    - { role: roles/cli_user  , rem_user: "deploy" }
    - { role: roles/cli_user  , rem_user: "aleak"  }
    - { role: roles/cli_user  , rem_user: "mgregg" }
    - roles/cli_tzone
    - roles/cli_base
    - roles/pips
    - roles/tmux
    - roles/hotspot_rpi
    - roles/gpsd
    - roles/cell_modem_support
    - { role: roles/call_home, rpi_name: "mgregg-rpi3.michaelgregg.com", relay_host: "www.michaelgregg.com:250", call_home_email: "mgregg@michaelgregg.com" }  
    - { role: roles/web_admin, deploy_user: "deploy" }
