---
# USE THE CONFIG SCRIPT TO BRING UP A NEW MACHINE

- hosts:      rpi   
  vars:
    - lcl_user:  "{{ lookup('env', 'USER') }}"
    - rem_user:  pi                
  remote_user: "{{rem_user}}"
  sudo: true
  roles:
    - { role: roles/setup_ssh , rem_user: "pi"     }      
    - { role: roles/cli_user  , rem_user: "aleak"  } 
    - { role: roles/cli_user  , rem_user: "mgregg" } 
    - roles/cli_tzone
    - roles/cli_base_rpi
    - roles/pips
    - roles/tmux_rpi
    - roles/hotspot_rpi
    - roles/gpsd
