---

# Setup hardware on power board.
# This will include setting up the RTC
# Then, the temperature sensor needs to be set up
# Finally, the ADC is to be enabled

- name: install support packages
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - i2c-tools  # Tools to interact with i2c bus
    - ntpdate    # Used to set time from upstream server
    - lm-sensors # Tool for reaing some ensors from the I2C bus

# Add lines to boot config to enable i2c
- lineinfile: dest=/boot/config.txt line="dtparam=i2c_arm=on"
- lineinfile: dest=/boot/config.txt line="dtparam=i2s=on"
- lineinfile: dest=/boot/config.txt line="dtparam=i2c1=on"
- lineinfile: dest=/boot/config.txt line="dtparam=i2c_arm=on"

- name: Enable the correct hardware modules on startup
  sudo: true
  copy: 
    backup: yes
    src: modules
    dest: /etc/modules
    mode: "a+rx"

- name: load i2c modules to enable getting to sensors
  sudo: true
  shell: /sbin/modprobe i2c-dev; /bin/modprobe i2c-bcm2708;

- name: install Real time clock init script
  sudo: true
  copy: 
    src: rtc
    dest: /etc/init.d/rtc
    mode: "a+rx"

# Enable RTC service
- service: name=rtc enabled=yes

- name: install script for reading from temp sensor
  sudo: true
  copy: 
    src: lm75b-read.py
    dest: /bin/lm75b-read.py
    mode: "a+rx"

# Copy over all support files for Voltage sensor
- name: Create needed sub dir
  sudo: true
  shell: mkdir /usr/bin/Adafruit_ADS1x15

- name: Copy voltage support file 1
  sudo: true
  copy: src=Adafruit_I2C.py dest=/usr/bin/Adafruit_I2C.py mode=755

- name: Copy voltage support file 2
  sudo: true
  copy: src=Adafruit_I2C.py dest=/usr/bin/Adafruit_ADS1x15/Adafruit_I2C.py mode=755

- name: Copy voltage support file 3
  sudo: true
  copy: src=Adafruit_ADS1x15.py dest=/usr/bin/Adafruit_ADS1x15.py mode=755

- name: Copy voltage support file 4
  sudo: true
  copy: src=Adafruit_ADS1x15.py dest=/usr/bin/Adafruit_ADS1x15/Adafruit_ADS1x15.py mode=755

- name: Copy voltage support file 5
  sudo: true
  copy: src=ads1x15_read_all.py dest=/usr/bin/ads1x15_read_all.py mode=755

